version: "3"

services:
  web:
    container_name: web
    build: ./api
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    volumes:
      - ./api:/app

  redis:
    image: "redis:alpine"

  worker:
    build:
      context: ./api
    hostname: worker
    entrypoint: celery
    command: -A app.celery worker --loglevel=info -E --pool='solo' # set --loglevel=debug to see detailed celery error
    volumes:
      - ./api:/app
    depends_on:
      - redis
